# -*- coding: utf-8 -*-
"""Pnemonia_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoUHOmRXmCQvX3tUiW8vTynP_WGyzXdm
"""

from google.colab import drive
drive.mount('/content/drive')

# Kaggle authentication & dataset download
import os

# Kaggle credentials
os.environ["KAGGLE_USERNAME"] = 'pranay121234'
os.environ['KAGGLE_KEY'] = "KGAT_3577e3912b6b6f35b4f6b7bb0b4e2440"

# Download dataset
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

# Unzip
!unzip -q chest-xray-pneumonia.zip -d chest_xray

# Optional: list folders to verify
!ls -l chest_xray/chest_xray

# 2 – Imports

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from PIL import Image
from sklearn.model_selection import train_test_split

# For displaying in Colab
from google.colab.patches import cv2_imshow

import tensorflow as tf
from tensorflow.keras import layers, models

# 3 – Count files & print sample names

base = "/content/chest_xray/chest_xray"

normal_test    = os.listdir(f"{base}/test/NORMAL")
normal_train   = os.listdir(f"{base}/train/NORMAL")
normal_val     = os.listdir(f"{base}/val/NORMAL")

pneu_test      = os.listdir(f"{base}/test/PNEUMONIA")
pneu_train     = os.listdir(f"{base}/train/PNEUMONIA")
pneu_val       = os.listdir(f"{base}/val/PNEUMONIA")

print("First 5 NORMAL test images:", normal_test[:5])
print("First 5 PNEUMONIA test images:", pneu_test[:5])

total_normal   = len(normal_test) + len(normal_train) + len(normal_val)
total_pneumonia = len(pneu_test) + len(pneu_train) + len(pneu_val)

print(f"Total NORMAL   images : {total_normal}")
print(f"Total PNEUMONIA images : {total_pneumonia}")

# 4 – Create labels

labels = [0] * total_normal + [1] * total_pneumonia

print("First 10 labels  :", labels[:10])
print("Last  10 labels  :", labels[-10:])
print("Total labels     :", len(labels))

# 5 – Show example images

# Normal
img_normal = mpimg.imread(f"{base}/test/NORMAL/IM-0039-0001.jpeg")
plt.figure(figsize=(6,6))
plt.title("Normal Chest X-ray")
plt.imshow(img_normal, cmap='gray')
plt.axis('off')
plt.show()

# Pneumonia
img_pneu = mpimg.imread(f"{base}/test/PNEUMONIA/person85_bacteria_417.jpeg")
plt.figure(figsize=(6,6))
plt.title("Pneumonia Chest X-ray")
plt.imshow(img_pneu, cmap='gray')
plt.axis('off')
plt.show()

# 6 – Load & preprocess all images (this takes time)

data = []

def load_images_from_folder(folder_path):
    files = os.listdir(folder_path)
    for img_file in files:
        try:
            img_path = os.path.join(folder_path, img_file)
            image = Image.open(img_path).convert("RGB")
            image = image.resize((128, 128))
            image = np.array(image)
            data.append(image)
        except Exception as e:
            print(f"Skipping {img_file} → {e}")

print("Loading NORMAL images...")
load_images_from_folder(f"{base}/train/NORMAL")
load_images_from_folder(f"{base}/test/NORMAL")
load_images_from_folder(f"{base}/val/NORMAL")

print("Loading PNEUMONIA images...")
load_images_from_folder(f"{base}/train/PNEUMONIA")
load_images_from_folder(f"{base}/test/PNEUMONIA")
load_images_from_folder(f"{base}/val/PNEUMONIA")

print(f"Total images loaded: {len(data)}")
print("Should match labels count →", len(data) == len(labels))

# 7 – Convert to numpy arrays

X = np.array(data)
Y = np.array(labels)

print("X shape:", X.shape)
print("Y shape:", Y.shape)

# 8 – Train-test split + normalization

x_train, x_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.2,
    random_state=2,
    stratify=Y
)

x_train = x_train / 255.0
x_test  = x_test  / 255.0

print("x_train shape:", x_train.shape)
print("x_test shape :", x_test.shape)

# 9 – Build CNN model

input_shape = (128, 128, 3)

model = models.Sequential([
    # Block 1
    layers.Conv2D(32, (3,3), padding='valid', input_shape=input_shape),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D((2,2)),

    # Block 2
    layers.Conv2D(64, (3,3), padding='valid'),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D((2,2)),

    # Block 3
    layers.Conv2D(128, (3,3), padding='valid'),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D((2,2)),

    # Block 4
    layers.Conv2D(256, (3,3), padding='valid'),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),

    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.4),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(2, activation='sigmoid')   # or softmax
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# 10 – Train the model

history = model.fit(
    x_train, y_train,
    epochs=10,                # ← you can increase
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

# 11 – Evaluation & plots

test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"\nTest Accuracy: {test_acc:.4f}  ({test_acc*100:.2f}%)")

# Plots
plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.title('Loss')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.title('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

# 12 – Save model

model.save("pneumonia_cnn_model.h5")
print("Model saved as pneumonia_cnn_model.h5")

# 13 – Inference on single image (upload or path)

from google.colab import files

print("Upload an image to test:")
uploaded = files.upload()

if uploaded:
    filename = list(uploaded.keys())[0]
    img = cv2.imread(filename)
    cv2_imshow(img)

    # Preprocess
    img_resized = cv2.resize(img, (128,128))
    img_scaled = img_resized / 255.0
    img_input = np.expand_dims(img_scaled, axis=0)   # shape (1,128,128,3)

    pred = model.predict(img_input)
    prob = pred[0]

    print("\nPredictions:", prob)
    label = np.argmax(prob)

    if label == 1:
        print(f"PNEUMONIA  (confidence: {prob[1]:.4f})")
    else:
        print(f"NORMAL     (confidence: {prob[0]:.4f})")

